// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { env } from "node:process";
import { defineConfig } from "prisma/config";

const databaseUrl = env.DATABASE_URL;
if (!databaseUrl) {
  throw new Error("Missing required env.DATABASE_URL");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
